# Change these first
owner: LuckyHookin # Your GitHub username
repo: hookin_fun_upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Hookin.fun
    url: https://hookin.fun
  - name: bingPict
    url: https://bing.hookin.fun
  - name: share
    url: https://share.hookin.fun
  - name: cleanData
    url: $CLEAN_DATA_URL


# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
